# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-17 20:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runtracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 17, 21, 4, 26, 578519)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='run',
            name='distance',
            field=models.FloatField(verbose_name='Distance(km)'),
        ),
        migrations.AlterField(
            model_name='run',
            name='duration',
            field=models.FloatField(verbose_name='Time(minutes)'),
        ),
    ]
