# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-19 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runtracker', '0002_auto_20160917_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='distance',
            field=models.FloatField(verbose_name='Distance (km)'),
        ),
        migrations.AlterField(
            model_name='run',
            name='duration',
            field=models.FloatField(verbose_name='Time (minutes)'),
        ),
    ]
