# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-22 18:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runtracker', '0004_userinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='age',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='dob',
            field=models.DateField(default=datetime.date(1999, 1, 18), verbose_name='Date of birth'),
            preserve_default=False,
        ),
    ]
